version: '2'
services:
 linuxserver-plex:
  container_name: plex
  restart: unless-stopped
  image: linuxserver/plex:latest
  environment:
   - TZ=America/Chicago
   - PUID = 911
   - PGID = 1001
  ports:
   - "32400:32400" #(for access to the Plex Media Server) [required]
   - "32400:32400/udp"
   - "32410:32410/udp" #(for current GDM network discovery)
   - "32412:32412/udp"
   - "32413:32413/udp"
   - "32414:32414/udp"
   - "32469:32469" #(for access to the Plex DLNA Server)
   - "32469:32469/udp"
   - "5353:5353" # (for older Bonjour/Avahi network discovery)
   - "1900:1900/udp" #(for access to the Plex DLNA Server)
  volumes:
   - /home/appadmin/plex/config:/config
   - /mnt/media/tv_shows:/data/tvshows
   - /mnt/media/movies:/data/movies
   - /media/brandon/My Book/Music:/data/Music
 linuxserver-radarr:
  container_name: radarr
  restart: unless-stopped
  image: linuxserver/radarr:latest
  ports:
   - "7878:7878"
  volumes:
   - /home/appadmin/plex/config:/config
   - /mnt/media/tv_shows:/data/tvshows
   - /mnt/media/movies:/data/movies
   - /media/brandon/My Book/Music/:/data/Music
   - /home/appadmin/radarr/config:/config
   - /home/appadmin/radarr/downloads:/downloads
   - /home/appadmin/radarr/movies:/movies
   - /etc/localtime:/etc/localtime:ro
   - /home/appadmin/transmission/complete:/data/completed
   - /home/appadmin/transmission/incomplete:/data/incomplete
   - /home/appadmin/sabnzbd/config/Downloads/complete:/config/Downloads/complete
   - /home/appadmin/sabnzbd/config/incomplete:/incomplete-downloads
  environment:
   - TZ=America/Chicago
   - PUID = 911
   - PGID = 1001
 transmission:
  image: haugene/transmission-openvpn
  cap_add:
    - NET_ADMIN
  devices:
   - /dev/net/tun
  restart: always
  ports:
    - "9091:9091"
    - "8888:8888"
  dns:
   - 8.8.8.8
   - 8.8.4.4
  volumes:
    - /etc/localtime:/etc/localtime:ro
    - /home/appadmin/plex/config:/config
    - /mnt/media/tv_shows:/data/tvshows
    - /mnt/media/movies:/data/movies
    - /media/brandon/My Book/Music:/data/Music
    - /home/appadmin/transmission/config:/config
    - /home/appadmin/transmission/download:/downloads
    - /home/appadmin/transmission/watch:/watch
    - /home/appadmin/transmission/complete:/data/completed
    - /home/appadmin/transmission/incomplete:/data/incomplete
  environment:
    - OPENVPN_PROVIDER=PIA
    - OPENVPN_USERNAME=${pia_uname}
    - OPENVPN_PASSWORD=${pia_pass}
    - OPENVPN_CONFIG=france
    - OPENVPN_OPTS=--inactive 3600 --ping 10 --ping-exit 60
    - LOCAL_NETWORK=192.168.0.0/16
    - WEBPROXY_ENABLED=false
    - PUID = 911
    - PGID = 1001
  security_opt:
    - seccomp:unconfined
 jackett:
  container_name: jackett
  restart: unless-stopped
  ports:
   - "9117:9117"
  image: linuxserver/jackett
  volumes:
   - /home/appadmin/jackett/config:/config
   - /home/appadmin/jackett/downloads:/download
   - /home/appadmin/sonarr:/data/config/sonarr
   - /home/appadmin/radarr:/data/config/radarr
   - /etc/localtime:/etc/localtime:ro
 sonarr:
  image: linuxserver/sonarr
  restart: unless-stopped
  container_name: sonarr
  environment:
   - TZ=America/Chicago
   - PUID = 911
   - PGID = 1001
  ports:
   - "8989:8989"
  volumes:
   - /etc/localtime:/etc/localtime:ro
   - /home/appadmin/sonarr/config:/config
   - /home/appadmin/sonarr/tv:/tv
   - /home/docker/sonarr/download:/downloads
   - /home/appadmin/transmission/complete:/data/completed
   - /home/appadmin/transmission/incomplete:/data/incomplete
   - /mnt/media/tv_shows:/data/tvshows
   - /mnt/media/movies:/data/movies
     # - /home/appadmin/jackett/config:/config
     # - /home/appadmin/jackett/downloads:/download
   - /home/appadmin/sabnzbd/config/Downloads/complete:/config/Downloads/complete
   - /home/appadmin/sabnzbd/config/incomplete:/incomplete-downloads
 portainer:
  image: portainer/portainer
  container_name: portainer
  restart: unless-stopped
  ports:
   - "9000:9000"
  volumes:
   - '/var/run/docker.sock:/var/run/docker.sock'
   - "/home/appadmin/portainer/configs/:/data"
 watchtower:
  image: v2tec/watchtower
  container_name: watchtower
  restart: unless-stopped
  volumes:
   - '/var/run/docker.sock:/var/run/docker.sock'
 bazarr:
  image: linuxserver/bazarr
  container_name: bazarr
  restart: unless-stopped
  environment:
   - TZ=America/Chicago
   - PUID = 911
   - PGID = 1001
  volumes:
   - /home/appadmin/bazarr/config:/config
   - /mnt/media/movies:/data/movies
   - /mnt/media/tv_shows:/data/tvshows
  ports:
   - "6767:6767"
     # organizr:
     # image: linuxserver/organizr
     # container_name: organizr
     # environment:
     # - PUID=911
     # - GUID=1001
     # - TZ=America/Chicago
     # volumes:
     # - '/home/appadmin/organizr/config:/config'
     # ports:
     # - 9983:80
     # restart: unless-stopped
 ombi:
  image: linuxserver/ombi
  container_name: ombi
  environment:
   - PUID= 911
   - GUID= 1001
   - TZ=America/Chicago
   - BASE_URL=/ombi
  volumes:
   - '/home/appadmin/ombi/config:/config'
  ports:
   - 3579:3579
  restart: unless-stopped
 tautulli:
  image: tautulli/tautulli
  container_name: tautulli
  environment:
   - PUID = 911
   - GUID = 1001
   - TZ=America/Chicago
  volumes:
   - '/home/appadmin/tautulli/config:/config'
   - '/home/appadmin/plex/config/logs:/plex_logs:ro'
  ports:
   - '8181:8181'
  restart: unless-stopped
 minecraft:
  image: itzg/minecraft-server
  container_name: minecraft
  ports:
  - "25565:25565"
  environment:
   EULA: "TRUE"
   SERVER_NAME: "Hello Michael"
   MOTD: "Peaceful World"
   DIFFICULTY: "peaceful"
   MEMORY: 4G
  tty: true
  stdin_open: true
  restart: unless-stopped
  volumes:
  - "/mnt/minecraft:/data"
  - "/mnt/minecraft/plugins:/data/plugins"
  - "/mnt/minecraft/mods:/data/mods"
 sabnzbdz:
  image: lscr.io/linuxserver/sabnzbd:latest
  environment:
   - PUID= 911
   - GUID= 1001
   - TZ=America/Chicago
  ports:
   - 8080:8080
  volumes:
   - "/etc/localtime:/etc/localtime:ro"
   - "/mnt/media/tv_shows:/data/tvshows"
   - "/mnt/media/movies:/data/movies"
   - "/home/appadmin/sabnzbd/config:/config"
  restart: unless-stopped
 homarr:
  image: ghcr.io/ajnart/homarr:latest
  restart: unless-stopped
  volumes:
   - "/home/appadmin/homarr/configs:/app/data/configs"
   - "/home/appadmin/homarr/icons:/app/public/icons"
  ports:
   - 7575:7575
  environment:
   - PUID = 911
   - GUID = 1001
   - TZ=America/Chicago
 prowlarr:
  image: lscr.io/linuxserver/prowlarr:latest
  container_name: prowlarr
  environment:
   - PUID= 911
   - GUID= 1001
   - TZ=America/Chicago
  volumes:
   - "/home/appadmin/prowlarr/config:/config"
  ports:
   - 9696:9696
  restart: unless-stopped
